name: Deploy to Ubuntu NGINX

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Landzone repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy files to server
      run: |
        rsync -avz ./land zone/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/html
 